---
- name: remove Raspberry Pi ssh-publickey
  hosts: 127.0.0.1
  tasks:
   - name: remove ssh publickey
     shell: ssh-keygen -R {{ inventory_hostname }}

- name: Setup IP Address + Reboot
  roles:
   - ipaddr_setup

- name: Setup Raspberry Pi
  hosts: raspi
  sudo: yes

  roles:
   - setup
