#- name: wait for SSH port down
#  local_action: wait_for host=groups['raspi-dhcp'][0] port=22 state=stopped
  #local_action: wait_for host=192.168.11.13 state=started delay=30 timeout=300

- name: wait for SSH port up
  local_action: wait_for host=groups['raspi-static'][0] state=started delay=1 timeout=300
  #local_action: wait_for host=192.168.11.13 state=started delay=1 timeout=300

